//! Build script: keeps the game's level assets in sync with the LDtk export,
//! and auto-registers every level by folder-name convention.
//!
//! ## Single source of truth
//!
//! LDtk's "Super Simple Export" writes each level to
//! `all-the-levels/simplified/<Name>/`. The game, however, embeds and reads
//! from `assets/levels/<Name>/` (the `assets/` tree also holds sprites/sounds,
//! so the levels have to live under it for `bevy_embedded_assets`). To stop the
//! two trees from drifting, this script mirrors the LDtk export into
//! `assets/levels/` on every build — copying only files that actually changed.
//! Edit a level in LDtk, export, rebuild: done. No manual copy.
//!
//! (One caveat: `bevy_embedded_assets` embeds `assets/` *before* this script
//! runs, so when an export changes a layer **PNG**, the embedded art refreshes
//! on the *next* build. Collision/entity data — read via `include_str!` of the
//! freshly-synced CSV/JSON — is correct on the first build. A `cargo:warning`
//! is emitted whenever a PNG is synced so the lag isn't silent.)
//!
//! ## Auto-registration (by folder name)
//!   * Trailing `<entrances>E<exits>X` segment (e.g. `Zen_Platforms_LELX`;
//!     each side is `L`, `R`, or both `LR`) → zen stitch piece (`ZEN_PIECE_NAMES`).
//!   * Other `Zen_*` folder (e.g. `Zen_bottom`) → zen base/aux: loadable, but
//!     not in the menu or the random pool.
//!   * Everything else (e.g. `Level_5`) → menu level, natural-sorted into
//!     `LEVEL_ORDER`.

use std::cmp::Ordering;
use std::env;
use std::fs;
use std::path::Path;

const SOURCE_REL: &str = "all-the-levels/simplified";
const DEST_REL: &str = "assets/levels";

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest_dir);
    let source_dir = root.join(SOURCE_REL);
    let dest_dir = root.join(DEST_REL);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={DEST_REL}");

    // 1. Mirror the LDtk export into assets/levels (best-effort; if the export
    //    folder is absent — e.g. a slim checkout — fall back to whatever is
    //    already committed under assets/levels).
    let mut png_synced = false;
    if source_dir.is_dir() {
        png_synced = sync_levels(&source_dir, &dest_dir);
    }
    if png_synced {
        println!(
            "cargo:warning=Synced updated layer PNG(s) from the LDtk export; \
             re-run the build to refresh embedded level art."
        );
    }

    // 2. Discover level folders (the synced copy) that have the data files we
    //    include_str!, and natural-sort them.
    let mut levels: Vec<String> = Vec::new();
    for entry in fs::read_dir(&dest_dir).expect("assets/levels directory must exist") {
        let entry = entry.expect("readable directory entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let has = |f: &str| path.join(f).is_file();
        if has("data.json") && has("Walls.csv") && has("Door.csv") {
            let name = entry.file_name().to_string_lossy().into_owned();
            println!("cargo:rerun-if-changed={DEST_REL}/{name}");
            levels.push(name);
        }
    }
    levels.sort_by(|a, b| natural_cmp(a, b));

    // 3. Classify by naming convention.
    let mut menu: Vec<&str> = Vec::new();
    let mut zen: Vec<&str> = Vec::new();
    for name in &levels {
        if is_zen_stitch(name) {
            zen.push(name);
        } else if name.starts_with("Zen_") {
            // Zen base/aux (e.g. Zen_bottom): loadable via level_files(), but
            // not a menu level and not part of the random stitch pool.
        } else {
            menu.push(name);
        }
    }

    // 4. Generate the registry.
    let root_fwd = manifest_dir.replace('\\', "/");
    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit by hand.\n\n");

    out.push_str("/// Levels shown in the level-select menu, in play order.\n");
    out.push_str("pub const LEVEL_ORDER: &[&str] = &[\n");
    for n in &menu {
        out.push_str(&format!("    {n:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Zen stitch pieces available to the infinite-climb generator.\n");
    out.push_str("pub const ZEN_PIECE_NAMES: &[&str] = &[\n");
    for n in &zen {
        out.push_str(&format!("    {n:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Embedded (data.json, Walls.csv, Door.csv) for a level folder.\n");
    out.push_str("fn level_files(name: &str) -> (&'static str, &'static str, &'static str) {\n");
    out.push_str("    match name {\n");
    for n in &levels {
        let data = format!("{root_fwd}/{DEST_REL}/{n}/data.json");
        let walls = format!("{root_fwd}/{DEST_REL}/{n}/Walls.csv");
        let door = format!("{root_fwd}/{DEST_REL}/{n}/Door.csv");
        out.push_str(&format!(
            "        {n:?} => (include_str!({data:?}), include_str!({walls:?}), include_str!({door:?})),\n"
        ));
    }
    out.push_str("        _ => panic!(\"Unknown level folder: {name}\"),\n");
    out.push_str("    }\n}\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("levels_generated.rs"), out)
        .expect("write generated level registry");
}

/// Mirror every level folder under `source` into `dest`, copying only files
/// whose bytes differ (so an in-sync tree is a no-op and the working tree stays
/// clean). Returns true if any `.png` was updated (embedded art lags one build).
fn sync_levels(source: &Path, dest: &Path) -> bool {
    let mut png_synced = false;
    for entry in fs::read_dir(source).expect("readable LDtk export") {
        let src_folder = entry.expect("readable entry").path();
        if !src_folder.is_dir() {
            continue;
        }
        let has = |f: &str| src_folder.join(f).is_file();
        if !(has("data.json") && has("Walls.csv") && has("Door.csv")) {
            continue; // not a level folder (e.g. backups/)
        }
        let name = src_folder.file_name().unwrap();
        let dst_folder = dest.join(name);
        fs::create_dir_all(&dst_folder).expect("create dest level folder");

        for file in fs::read_dir(&src_folder).expect("readable source folder") {
            let src_file = file.expect("readable entry").path();
            if !src_file.is_file() {
                continue;
            }
            // Re-run this build script whenever a source file changes — a plain
            // rerun-if-changed on the directory misses edits to existing files.
            println!("cargo:rerun-if-changed={}", rel(src_file.as_path()));

            let dst_file = dst_folder.join(src_file.file_name().unwrap());
            if files_differ(&src_file, &dst_file) {
                fs::copy(&src_file, &dst_file).expect("copy level file");
                if src_file.extension().is_some_and(|e| e == "png") {
                    png_synced = true;
                }
            }
        }
    }
    png_synced
}

/// Path relative to the manifest dir, forward-slashed (for cargo directives).
fn rel(path: &Path) -> String {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    path.strip_prefix(&manifest_dir)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn files_differ(src: &Path, dst: &Path) -> bool {
    match (fs::read(src), fs::read(dst)) {
        (Ok(a), Ok(b)) => a != b,
        _ => true,
    }
}

/// True if `name`'s trailing `_`-segment matches the zen stitch convention
/// `<entrances>E<exits>X`, where each side is a non-empty subset of {L, R}.
fn is_zen_stitch(name: &str) -> bool {
    let suffix = name.rsplit('_').next().unwrap_or("");
    let (Some(e), Some(x)) = (suffix.find('E'), suffix.find('X')) else {
        return false;
    };
    if e >= x || x != suffix.len() - 1 {
        return false;
    }
    let side_ok = |s: &str| !s.is_empty() && s.chars().all(|c| c == 'L' || c == 'R');
    side_ok(&suffix[..e]) && side_ok(&suffix[e + 1..x])
}

/// Compare names so digit runs sort numerically (`Level_2` before `Level_10`).
fn natural_cmp(a: &str, b: &str) -> Ordering {
    let mut ai = a.bytes().peekable();
    let mut bi = b.bytes().peekable();
    loop {
        match (ai.peek().copied(), bi.peek().copied()) {
            (None, None) => return Ordering::Equal,
            (None, Some(_)) => return Ordering::Less,
            (Some(_), None) => return Ordering::Greater,
            (Some(ca), Some(cb)) => {
                let ord = if ca.is_ascii_digit() && cb.is_ascii_digit() {
                    take_number(&mut ai).cmp(&take_number(&mut bi))
                } else {
                    ai.next();
                    bi.next();
                    ca.cmp(&cb)
                };
                if ord != Ordering::Equal {
                    return ord;
                }
            }
        }
    }
}

fn take_number<I: Iterator<Item = u8>>(it: &mut std::iter::Peekable<I>) -> u64 {
    let mut n = 0u64;
    while let Some(&c) = it.peek() {
        if !c.is_ascii_digit() {
            break;
        }
        n = n.saturating_mul(10).saturating_add((c - b'0') as u64);
        it.next();
    }
    n
}
