//! Loads levels and builds the world from LDtk data.
//!
//! Turns each level's exported `data.json` + IntGrid CSVs (Walls / Door /
//! Slippy) into colliders, layer sprites, and entities (player spawn,
//! checkpoints, keys, wall writing, tutorial triggers). Also holds the Zen
//! "stitch pieces together" generator (`build_zen_world`). The level registry
//! it reads (`LEVEL_ORDER`, `ZEN_PIECE_NAMES`, `level_files`) is code-generated
//! by build.rs — see DOCS/ARCHITECTURE.md, "Adding content".

use avian2d::prelude::*;
use bevy::prelude::*;
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};
use serde::Deserialize;

use crate::level::{merge_grid_to_rects, Checkpoint, GamePhase, LevelEntity};
use crate::player::Player;
use crate::tutorial::TutorialTrigger;
use crate::walls::{SlippyWall, Wall};

// Auto-generated by build.rs from the folders under `assets/levels/`:
//   - `LEVEL_ORDER`     — menu levels, in play order
//   - `ZEN_PIECE_NAMES` — zen stitch pieces for the infinite-climb generator
//   - `level_files`     — embedded (data.json, Walls.csv, Door.csv) per folder
include!(concat!(env!("OUT_DIR"), "/levels_generated.rs"));

const TILE: f32 = 16.0;
const LEVEL_PX: f32 = 640.0;

#[derive(Component)]
pub struct KeyPickup;

#[derive(Component)]
pub struct DoorWall;

#[derive(Component)]
pub struct DoorSprite;

/// Decorative hint art painted on a wall (e.g. the "jump" prompt).
#[derive(Component)]
pub struct WallWriting;

pub struct LdtkPlugin;

impl Plugin for LdtkPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            Update,
            key_pickup.run_if(in_state(GamePhase::Playing)),
        );
    }
}

#[derive(Resource)]
pub struct CurrentLevel(pub usize);

impl Default for CurrentLevel {
    fn default() -> Self {
        Self(0)
    }
}

impl CurrentLevel {
    pub fn name(&self) -> &'static str {
        LEVEL_ORDER[self.0]
    }

    /// Advance to next level. Returns true if there is a next level.
    pub fn advance(&mut self) -> bool {
        if self.0 + 1 < LEVEL_ORDER.len() {
            self.0 += 1;
            true
        } else {
            false
        }
    }
}

#[derive(Deserialize)]
struct LevelData {
    #[serde(default = "default_level_px")]
    width: f32,
    #[serde(default = "default_level_px")]
    height: f32,
    layers: Vec<String>,
    entities: Entities,
}

fn default_level_px() -> f32 {
    640.0
}

#[derive(Deserialize)]
struct Entities {
    #[serde(default)]
    #[serde(rename = "PlayerSpawn")]
    player_spawn: Vec<EntityEntry>,
    #[serde(default)]
    #[serde(rename = "Checkpoint")]
    checkpoint: Vec<EntityEntry>,
    #[serde(default)]
    #[serde(rename = "Key")]
    key: Vec<EntityEntry>,
    #[serde(default)]
    #[serde(rename = "WallWriting")]
    wall_writing: Vec<WritingEntry>,
    #[serde(default)]
    #[serde(rename = "TutorialText")]
    tutorial_text: Vec<TutorialEntry>,
}

#[derive(Deserialize)]
struct EntityEntry {
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

#[derive(Deserialize)]
struct WritingEntry {
    x: f32,
    y: f32,
    width: f32,
    height: f32,
    #[serde(rename = "customFields", default)]
    fields: WritingFields,
}

#[derive(Deserialize, Default)]
struct WritingFields {
    /// LDtk `WritingType` enum value (e.g. "Jump"); empty if unset.
    #[serde(rename = "WritingID", default)]
    writing_id: String,
}

#[derive(Deserialize)]
struct TutorialEntry {
    x: f32,
    y: f32,
    width: f32,
    height: f32,
    #[serde(rename = "customFields", default)]
    fields: TutorialFields,
}

#[derive(Deserialize, Default)]
struct TutorialFields {
    /// LDtk `TutorialTextType` enum value (e.g. "Press_XJUMPX_To_Jump").
    #[serde(rename = "TutorialTextType", default)]
    text_type: String,
}

/// Sprite path for a wall-writing, by naming convention: the LDtk `WritingID`
/// enum value, lower-cased, under `assets/writing/`. To add a new writing,
/// add a value to the `WritingType` enum in LDtk and drop `<id>.png` (lower-
/// case) into `assets/writing/` — no code change needed here.
fn writing_asset_path(id: &str) -> String {
    format!("writing/{}.png", id.to_lowercase())
}

/// Convert LDtk y-down position (top-left origin) to Bevy y-up center position.
fn ldtk_to_bevy(x: f32, y: f32, w: f32, h: f32) -> Vec2 {
    Vec2::new(x + w / 2.0, LEVEL_PX - y - h / 2.0)
}

/// Parse an LDtk IntGrid "super simple" CSV into a bottom-up bool grid
/// (true = filled). LDtk row 0 is the top; Bevy row 0 is the bottom.
fn parse_grid(csv: &str) -> Vec<Vec<bool>> {
    let mut grid: Vec<Vec<bool>> = csv
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            line.split(',')
                .filter(|s| !s.trim().is_empty())
                .map(|s| s.trim() == "1")
                .collect()
        })
        .collect();
    grid.reverse();
    grid
}

pub fn build_ldtk_level(commands: &mut Commands, asset_server: &AssetServer, level_name: &str) -> Vec2 {
    let (data_str, csv_str, door_csv_str, slippy_csv_str) = level_files(level_name);

    let data: LevelData = serde_json::from_str(data_str).expect("Failed to parse LDtk data.json");

    // Parse Walls.csv into a bool grid
    let mut grid: Vec<Vec<bool>> = Vec::new();
    for line in csv_str.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let row: Vec<bool> = line
            .split(',')
            .filter(|s| !s.trim().is_empty())
            .map(|s| s.trim() == "1")
            .collect();
        grid.push(row);
    }

    // Flip rows: LDtk row 0 = top, Bevy row 0 = bottom
    grid.reverse();

    let rects = merge_grid_to_rects(&grid);

    // Spawn level root
    let level_entity = commands
        .spawn((
            LevelEntity,
            Transform::default(),
            Visibility::default(),
        ))
        .id();

    // Level center for sprite positioning
    let center = Vec3::new(LEVEL_PX / 2.0, LEVEL_PX / 2.0, 0.0);

    commands.entity(level_entity).with_children(|parent| {
        // Spawn layer images behind gameplay sprites
        for (i, layer_file) in data.layers.iter().enumerate() {
            let path = format!("levels/{}/{}", level_name, layer_file);
            let tf = Transform::from_translation(center + Vec3::new(0.0, 0.0, -10.0 + i as f32));
            if layer_file == "Door.png" {
                parent.spawn((
                    DoorSprite,
                    Sprite::from_image(asset_server.load(&path)),
                    tf,
                ));
            } else {
                parent.spawn((
                    Sprite::from_image(asset_server.load(&path)),
                    tf,
                ));
            }
        }

        // Spawn invisible wall colliders (visuals come from layer PNGs)
        for rect in &rects {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0;

            parent.spawn((
                Wall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Spawn checkpoint sensors
        for cp in &data.entities.checkpoint {
            let pos = ldtk_to_bevy(cp.x, cp.y, cp.width, cp.height);
            parent.spawn((
                Checkpoint,
                Collider::rectangle(cp.width, cp.height),
                Sensor,
                RigidBody::Static,
                Sprite::from_color(
                    Color::srgba(0.2, 0.9, 0.3, 0.4),
                    Vec2::new(cp.width, cp.height),
                ),
                Transform::from_xyz(pos.x, pos.y, 5.0),
            ));
        }

        // Parse and spawn door colliders
        let mut door_grid: Vec<Vec<bool>> = Vec::new();
        for line in door_csv_str.lines() {
            if line.trim().is_empty() {
                continue;
            }
            let row: Vec<bool> = line
                .split(',')
                .filter(|s| !s.trim().is_empty())
                .map(|s| s.trim() == "1")
                .collect();
            door_grid.push(row);
        }
        door_grid.reverse();

        let door_rects = merge_grid_to_rects(&door_grid);
        for rect in &door_rects {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0;

            parent.spawn((
                DoorWall,
                Wall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Slippy walls — collide + wall-slide like walls, but no wall-jump.
        for rect in &merge_grid_to_rects(&parse_grid(slippy_csv_str)) {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0;
            parent.spawn((
                Wall,
                SlippyWall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Spawn key pickups
        for key in &data.entities.key {
            let pos = ldtk_to_bevy(key.x, key.y, key.width, key.height);
            parent.spawn((
                KeyPickup,
                Collider::rectangle(key.width * 1.5, key.height * 1.5),
                Sensor,
                RigidBody::Static,
                Sprite::from_image(asset_server.load("key.png")),
                Transform::from_xyz(pos.x, pos.y, 5.0),
            ));
        }

        // Wall writing — decorative hint art on the wall, behind the player.
        for wr in &data.entities.wall_writing {
            if wr.fields.writing_id.is_empty() {
                continue;
            }
            let pos = ldtk_to_bevy(wr.x, wr.y, wr.width, wr.height);
            parent.spawn((
                WallWriting,
                Sprite::from_image(asset_server.load(writing_asset_path(&wr.fields.writing_id))),
                Transform::from_xyz(pos.x, pos.y, -1.0),
            ));
        }

        // Tutorial prompts — invisible sensor zones; text shows on player touch.
        for tt in &data.entities.tutorial_text {
            if tt.fields.text_type.is_empty() {
                continue;
            }
            let pos = ldtk_to_bevy(tt.x, tt.y, tt.width, tt.height);
            parent.spawn((
                TutorialTrigger {
                    text: tt.fields.text_type.clone(),
                },
                Collider::rectangle(tt.width, tt.height),
                Sensor,
                RigidBody::Static,
                Transform::from_xyz(pos.x, pos.y, 0.0),
                Visibility::Hidden,
            ));
        }
    });

    // Return spawn point from PlayerSpawn entity
    let sp = if let Some(ps) = data.entities.player_spawn.first() {
        ldtk_to_bevy(ps.x, ps.y, ps.width, ps.height)
    } else {
        Vec2::new(LEVEL_PX / 2.0, TILE * 3.0)
    };

    info!("Loaded LDtk level {} (spawn at {:?})", level_name, sp);

    sp
}

// --- Zen level stitching ---

/// Parse entrance/exit sides from a zen piece name.
/// Returns ((left_entrance, right_entrance), (left_exit, right_exit))
pub fn parse_zen_sides(name: &str) -> ((bool, bool), (bool, bool)) {
    // Find the last segment after the last underscore that contains E and X
    let suffix = name.rsplit('_').next().unwrap_or("");
    let e_pos = suffix.find('E');
    let x_pos = suffix.find('X');

    match (e_pos, x_pos) {
        (Some(e), Some(x)) if e < x => {
            let entrance_str = &suffix[..e];
            let exit_str = &suffix[e + 1..x];
            let entrances = (entrance_str.contains('L'), entrance_str.contains('R'));
            let exits = (exit_str.contains('L'), exit_str.contains('R'));
            (entrances, exits)
        }
        _ => ((true, true), (true, true)), // Fallback: open on all sides
    }
}

/// Pick a random compatible zen piece whose entrance overlaps the previous exit.
pub fn pick_zen_piece(rng: &mut StdRng, last_exits: (bool, bool)) -> &'static str {
    let compatible: Vec<&&str> = ZEN_PIECE_NAMES
        .iter()
        .filter(|name| {
            let (entrances, _) = parse_zen_sides(name);
            (last_exits.0 && entrances.0) || (last_exits.1 && entrances.1)
        })
        .collect();

    if compatible.is_empty() {
        // Fallback: pick any piece
        ZEN_PIECE_NAMES[rng.random_range(0..ZEN_PIECE_NAMES.len())]
    } else {
        compatible[rng.random_range(0..compatible.len())]
    }
}

/// Spawn a single zen piece as children of `level_entity`, offset vertically by `y_offset`.
/// Returns the piece height in pixels.
pub fn spawn_zen_piece(
    commands: &mut Commands,
    asset_server: &AssetServer,
    level_entity: Entity,
    name: &str,
    y_offset: f32,
) -> f32 {
    let (data_str, csv_str, door_csv_str, slippy_csv_str) = level_files(name);
    let data: LevelData = serde_json::from_str(data_str).expect("Failed to parse zen level data");

    let piece_h = data.height;

    // Parse walls
    let mut grid: Vec<Vec<bool>> = Vec::new();
    for line in csv_str.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let row: Vec<bool> = line
            .split(',')
            .filter(|s| !s.trim().is_empty())
            .map(|s| s.trim() == "1")
            .collect();
        grid.push(row);
    }
    grid.reverse();

    let rects = merge_grid_to_rects(&grid);

    // Parse doors
    let mut door_grid: Vec<Vec<bool>> = Vec::new();
    for line in door_csv_str.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let row: Vec<bool> = line
            .split(',')
            .filter(|s| !s.trim().is_empty())
            .map(|s| s.trim() == "1")
            .collect();
        door_grid.push(row);
    }
    door_grid.reverse();
    let door_rects = merge_grid_to_rects(&door_grid);
    let slippy_rects = merge_grid_to_rects(&parse_grid(slippy_csv_str));

    let center_x = data.width / 2.0;
    let center_y = piece_h / 2.0 + y_offset;

    commands.entity(level_entity).with_children(|parent| {
        // Layer images
        for (i, layer_file) in data.layers.iter().enumerate() {
            let path = format!("levels/{}/{}", name, layer_file);
            let tf = Transform::from_xyz(center_x, center_y, -10.0 + i as f32);
            if layer_file == "Door.png" {
                parent.spawn((
                    DoorSprite,
                    Sprite::from_image(asset_server.load(&path)),
                    tf,
                ));
            } else {
                parent.spawn((
                    Sprite::from_image(asset_server.load(&path)),
                    tf,
                ));
            }
        }

        // Wall colliders
        for rect in &rects {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0 + y_offset;

            parent.spawn((
                Wall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Door colliders
        for rect in &door_rects {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0 + y_offset;

            parent.spawn((
                DoorWall,
                Wall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Slippy walls — collide + wall-slide like walls, but no wall-jump.
        for rect in &slippy_rects {
            let w = (rect.right - rect.left + 1) as f32 * TILE;
            let h = (rect.top - rect.bottom + 1) as f32 * TILE;
            let cx = (rect.left + rect.right + 1) as f32 * TILE / 2.0;
            let cy = (rect.bottom + rect.top + 1) as f32 * TILE / 2.0 + y_offset;
            parent.spawn((
                Wall,
                SlippyWall,
                Collider::rectangle(w, h),
                RigidBody::Static,
                Friction::new(0.0),
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }

        // Wall writing — decorative hint art on the wall, behind the player.
        for wr in &data.entities.wall_writing {
            if wr.fields.writing_id.is_empty() {
                continue;
            }
            let cx = wr.x + wr.width / 2.0;
            let cy = piece_h - wr.y - wr.height / 2.0 + y_offset;
            parent.spawn((
                WallWriting,
                Sprite::from_image(asset_server.load(writing_asset_path(&wr.fields.writing_id))),
                Transform::from_xyz(cx, cy, -1.0),
            ));
        }

        // Tutorial prompts — invisible sensor zones; text shows on player touch.
        for tt in &data.entities.tutorial_text {
            if tt.fields.text_type.is_empty() {
                continue;
            }
            let cx = tt.x + tt.width / 2.0;
            let cy = piece_h - tt.y - tt.height / 2.0 + y_offset;
            parent.spawn((
                TutorialTrigger {
                    text: tt.fields.text_type.clone(),
                },
                Collider::rectangle(tt.width, tt.height),
                Sensor,
                RigidBody::Static,
                Transform::from_xyz(cx, cy, 0.0),
                Visibility::Hidden,
            ));
        }
    });

    piece_h
}

/// Build the initial zen world: spawn Zen_bottom + a buffer of pieces ahead.
/// Returns (spawn_point, level_entity, frontier_y, last_exits, rng).
pub fn build_zen_world(
    commands: &mut Commands,
    asset_server: &AssetServer,
    seed: u64,
) -> (Vec2, Entity, f32, (bool, bool), StdRng) {
    let mut rng = StdRng::seed_from_u64(seed);

    let level_entity = commands
        .spawn((
            LevelEntity,
            Transform::default(),
            Visibility::default(),
        ))
        .id();

    // Spawn Zen_bottom at y=0
    let bottom_h = spawn_zen_piece(commands, asset_server, level_entity, "Zen_bottom", 0.0);

    // Get spawn point from Zen_bottom data
    let (data_str, _, _, _) = level_files("Zen_bottom");
    let data: LevelData = serde_json::from_str(data_str).unwrap();
    let sp = if let Some(ps) = data.entities.player_spawn.first() {
        // LDtk y-down to Bevy y-up
        Vec2::new(ps.x + ps.width / 2.0, bottom_h - ps.y - ps.height / 2.0)
    } else {
        Vec2::new(320.0, TILE * 3.0)
    };

    let mut frontier_y = bottom_h;
    let mut last_exits = (true, true); // Zen_bottom is open on both sides

    // Pre-generate 8 pieces ahead
    for _ in 0..8 {
        let piece_name = pick_zen_piece(&mut rng, last_exits);
        let (_, exits) = parse_zen_sides(piece_name);
        let piece_h = spawn_zen_piece(commands, asset_server, level_entity, piece_name, frontier_y);
        frontier_y += piece_h;
        last_exits = exits;
    }

    info!("Built zen world (seed {}, frontier at {})", seed, frontier_y);

    (sp, level_entity, frontier_y, last_exits, rng)
}

fn key_pickup(
    mut commands: Commands,
    collisions: Collisions,
    player_query: Query<Entity, With<Player>>,
    key_query: Query<Entity, With<KeyPickup>>,
    door_query: Query<Entity, With<DoorWall>>,
    door_sprite_query: Query<Entity, With<DoorSprite>>,
) {
    let Ok(player) = player_query.single() else {
        return;
    };

    for key in &key_query {
        if collisions.contains(player, key) {
            commands.entity(key).despawn();
            for door in &door_query {
                commands.entity(door).despawn();
            }
            for sprite in &door_sprite_query {
                commands.entity(sprite).despawn();
            }
            return;
        }
    }
}
